apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: auths.v3.vmware.com
spec:
  group: v3.vmware.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object  
            properties:
              authmgmt:
                type: object
                properties:
                  global_permission_list:
                    type: array
                    items:
                      type: object
                      properties:
                       principal:
                        type: object
                        properties:
                          name:
                            type: string
                          group:
                            type: string
                  local_permission_list:
                    type: array
                    items:
                      type: object
                      properties:
                       principal:
                        type: object
                        properties:
                          name:
                            type: string
                          group:
                            type: string
                  ssh:
                    type: string
                  smtp:
                    type: string 
                  rsync:
                    type: string
                  ftp:
                    type: string                             
  scope: Namespaced
  names:
    plural: auths
    singular: auth
    kind: Auth
    shortNames:
    - au  
                        