apiVersion: "ipm.k8.vmware.com/v1"
kind: Desiredstate
metadata:
  name: desiredstates.ipm.k8.vmware.com
spec:
  desired_state:
    appliance:
       software_update_policy:
        password: "1234567"
        auto_stage: "ENABLED"
        hour: 23
        defaultURL: "http://d.com"
        customURL: "http://c.com"
        day: MONDAY
        minute: 59
       time_sync:
        mode: NTP
       smtp:
        relay_port: "1234"
        mail_server: "map://dummy.com" 
       ssh: 
        enabled: false
       local_accounts_policy:
        warn_days: 2
        max_days: 10
        min_days: 5 
       consoleCli: 
        enabled: true
       ntp:
        servers: [ "198.0.0.1", "198.0.0.2"]
       syslog:
        - hostname: "198.0.0.1"
          protocol: TLS
          port: 1
        - hostname: "198.0.0.2"
          protocol: UDP
          port: 1 
       time_zone: 
        name: "IST"
       network:
        dns_server_configuration:
          mode: DHCP
          servers: [ "198.0.0.1", "198.0.0.2"]
        firewall_rule_policies:
        - address: "198.0.0.1"
          prefix: 1
          interface_name: "NAC"
          policy: IGNORE
        - address: "198.0.0.2"
          prefix: 1
          interface_name: "NAC"
          policy: IGNORE
        proxy_configuration:
        - server: "198.0.0.1"
          protocol: HTTP
          password: "123456"
          port: 1
          enabled: true
          username: "test"
        - server: "198.0.0.2"
          protocol: HTTP
          password: "123456"
          port: 1
          enabled: true
          username: "test2"
       backup_schedules:
        - recurrence_info:
            hour: 1
            days: [MONDAY, SUNDAY]
            minute: 1
          backup_password: "123456"
          enable: true
          parts: ["value1", "value2"]
          location: "http://myurl.com"
          location_password: "123456"
          schedule_id: "1"
          location_user: "/home/test/"
          retention_info:
            max_count: 1
        - recurrence_info:
            hour: 1
            days: [MONDAY, SATURDAY]
            minute: 1
          backup_password: "123456"
          enable: true
          parts: ["value1", "value2"]
          location: "http://myurl.com"
          location_password: "123456"
          schedule_id: "1"
          location_user: "/home/test/"
          retention_info:
            max_count: 1
       root_local_account:
        warn_days_before_password_expiration: 1
        password: "123456"
        min_days_between_password_change: 1
        roles: [ "Backup" ,"Restore"]
        password_expires_at: '2015-01-01T22:13:05.651Z'
        fullname: "Admin"
        last_password_change: '2015-01-01T22:13:05.651Z'
        enabled: true
        email: "dummy@vmware.com"
        has_password: true
        max_days_between_password_change: 1
       shell:
        enabled: true
        timeout: 1    
       dcui: 
        enabled: true
       