apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: desiredstates.ipm.k8.vmware.com
spec:
  group: ipm.k8.vmware.com
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: desiredstates
    singular: desiredstate
    kind: Desiredstate
    shortNames:
    - ds
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
              name:
                type: string
              description:
                type: string
              desired_state:
                type: object
                properties:
                  appliance:
                    type: object
                    required:
                      - ssh
                      - dcui
                      - consoleCli
                      - shell
                    properties:
                      software_update_policy:
                        type: object
                        properties:
                          password:
                            type: string
                          auto_stage:
                            type: string
                            enum: [DISABLED, ENABLED, _UNKNOWN]
                            description: >
                               * `DISABLED` - disabled auto stage
                               * `ENABLED` - enable auto stage
                          hour:
                            type: integer
                            minimum: 0
                            maximum: 23
                          defaultURL:
                            type: string
                          customURL:
                            type: string
                          day:
                            type: string
                            enum: [MONDAY, TUESDAY, FRIDAY, WEDNESDAY, THURSDAY, SATURDAY, SUNDAY, EVERYDAY, _UNKNOWN]
                          minute:
                            type: integer
                            minimum: 0
                            maximum: 59
                          username:
                            type: string
                      time_sync:
                        type: object
                        properties:
                          mode:
                            type: string
                            enum: [DISABLED, NTP, HOST, _UNKNOWN]
                      smtp:
                        type: object
                        properties:
                          relay_port:
                            type: string
                          mail_server:
                            type: string
                      ssh:
                        type: object
                        properties:
                          enabled:
                            type: boolean
                      local_accounts_policy:
                        type: object
                        properties:
                          warn_days:
                            type: integer
                          max_days:
                            type: integer
                          min_days:
                            type: integer
                      consoleCli:
                        type: object
                        properties:
                          enabled:
                            type: boolean
                      ntp:
                        type: object
                        properties:
                          servers:
                            type: array
                            items:
                              type: string
                      syslog:
                        type: array
                        items:
                          type: object
                          properties:
                            hostname:
                              type: string
                            protocol:
                              type: string
                              enum: [TLS, UDP, TCP, _UNKNOWN]
                            port:
                              type: integer
                      time_zone:
                        type: object
                        properties:
                          name:
                            type: string
                      network:
                        type: object
                        properties:
                          dns_server_configuration:
                            type: object
                            properties:
                              mode:
                                type: string
                                enum: [DHCP, STATIC, _UNKNOWN]
                              servers:
                                type: array
                                items:
                                  type: string
                          firewall_rule_policies:
                            type: array
                            items:
                              type: object
                              properties:
                                address:
                                  type: string
                                prefix:
                                  type: integer
                                interface_name:
                                  type: string
                                policy:
                                  type: string
                                  enum: [IGNORE, ACCEPT, REJECT, RETURN, _UNKNOWN]
                          proxy_configuration:
                            type: array
                            items:
                              type: object
                              properties:
                                server:
                                  type: string
                                protocol:
                                  type: string
                                  enum: [HTTP, HTTPS, FTP, _UNKNOWN]
                                password:
                                  type: string
                                port:
                                  type: integer
                                enabled:
                                  type: boolean
                                username:
                                  type: string
                      backup_schedules:
                        type: array
                        items:
                          type: object
                          properties:
                            recurrence_info:
                              type: object
                              properties:
                                hour:
                                  type: integer
                                  minimum: 0
                                  maximum: 23
                                days:
                                  type: array
                                  items:
                                    type: string
                                    enum: [MONDAY, TUESDAY, FRIDAY, WEDNESDAY, THURSDAY, SATURDAY, SUNDAY, EVERYDAY, _UNKNOWN]
                                minute:
                                  type: integer
                                  minimum: 0
                                  maximum: 59
                            backup_password:
                              type: string
                            enable:
                              type: boolean
                            parts:
                              type: array
                              items:
                                type: string
                            location:
                              type: string
                            location_password:
                              type: string
                            schedule_id:
                              type: string
                            location_user:
                              type: string
                            retention_info:
                              type: object
                              properties:
                                max_count:
                                  type: integer
                      shell:
                        type: object
                        properties:
                          enabled:
                            type: boolean
                          timeout:
                            type: integer
                      root_local_account:
                        type: object
                        properties:
                          warn_days_before_password_expiration:
                            type: integer
                          password:
                            type: string
                          min_days_between_password_change:
                            type: integer
                          roles:
                            type: array
                            items:
                              type: string
                          password_expires_at:
                            type: string
                          fullname:
                            type: string
                          last_password_change:
                            type: string
                          enabled:
                            type: boolean
                          email:
                            type: string
                          has_password:
                            type: boolean
                          max_days_between_password_change:
                            type: integer
                      dcui:
                        type: object
                        properties:
                          enabled:
                            type: boolean
