apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: testresources.k8.poc.github.com
spec:
  group: k8.poc.github.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object  
            properties:
              testmgmt:
                type: object
                properties:
                  global_permission_list:
                    type: array
                    items:
                      type: object
                      properties:
                       principal:
                        type: object
                        properties:
                          name:
                            type: string
                          group:
                            type: string
                  local_permission_list:
                    type: array
                    items:
                      type: object
                      properties:
                       principal:
                        type: object
                        properties:
                          name:
                            type: string
                          group:
                            type: string
                  ssh:
                    type: string
                  smtp:
                    type: string 
                  rsync:
                    type: string
                  ftp:
                    type: string
                  notification:
                    type: string
                  ntp: 
                    type: string
                  sftp:
                    type: string
                  time_zone:
                    type: string                                     
  scope: Namespaced
  names:
    plural: testresources
    singular: testresource
    kind: TestResource
    shortNames:
    - tr 
                        